### ISSUE TITLE
About node feature?

### ISSUE THREAD

**Issue by jiajunCAU** [HKUDS/OpenGraph#3]
Hello, this work is very promising, however, I have some questions.
Is the dataset not using any node features?  Because OpenGraph directly using SVD to generate the node tokenizer based on the processed adjacency matrix.

**Comment by akaxlh** [comment]
Hi, thank you for your attention to this work. 

The current released version does not utilize node features. However, we have been testing some potential solutions to address this limitation, and preliminary results show effectiveness on the current datasets. The main approach involves transforming node features into graph structures.

**Comment by jiajunCAU** [comment]
Thank you!
