### ISSUE TITLE
Parameterization of node features

### ISSUE THREAD

**Issue by mt-cly** [HKUDS/OpenGraph#5]
Hi,
Thanks for your great work. 
I have some confusions  about https://github.com/HKUDS/OpenGraph/blob/main/link_prediction/model.py#L31 . It seems that features obtained from svd_proj is warped as parameter and involved during training. Why does make such feature trainable? It is just like we make an input is trainable, which confused me a lot.
Looking forward your reply.

**Comment by wuhaoxz** [comment]
![image](https://github.com/user-attachments/assets/55470c41-ca6f-4ed8-9e14-4a9efe5c0f8a)
![image](https://github.com/user-attachments/assets/6db95004-9090-4644-b0a3-27a7d5166d2a)

代码里的优化器好像只优化OpenGraph模型里的参数， 虽然将特征作为参数，但其实好像是不被优化的。你可以运行代码打印看看是否特征真被训练，我没运行过
 @mt-cly

**Comment by akaxlh** [comment]
Thank @mt-cly for raising the issues, and thank @wuhaoxz for answering it. Indeed, although we wrap the features in nn.Parameter, they are not included as trainable parameters in the optimizer. Wrapping the features in nn.Parameter might have led to some confusion. This writing style is only a legacy one. I believe in old versions of the code, I tested learning independent embeddings which needs this wrapping.
