### ISSUE TITLE
Question about using OpenGraph on large-scale node classification datasets.

### ISSUE THREAD

**Issue by xioacd99** [HKUDS/OpenGraph#6]
The data formats used in OpenGraph are "adj_-1.pkl", "adj_1.pkl", "mask_1.pkl", and in [issue 4](https://github.com/HKUDS/OpenGraph/issues/4) you provided a script to convert the original data to these formats.

However, you load the entire dataset at once in the script, which is unacceptable for large-scale datasets like ogbn-*, which have nodes ranging from 2M to 100M.

I noticed that the largest dataset used in the paper is OGBL-collab, which has about 0.2M nodes, and I wonder if OpenGraph can be used for super large datasets, such as obgn-papers100M, which has about 100M nodes.

**Comment by akaxlh** [comment]
Thank you for bringing up this issue. I believe this problem is common to both foundation models and vanilla GNNs, so my suggestion would be to try graph sampling algorithms which can reduce computations by focusing on important subgraph structures.
